name: jamugo
description: "JamuGo, Pesan jamu dan minuman herbal tradisional Indonesia dengan mudah dan cepat langsung dari smartphone Anda."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  go_router: ^14.1.2
  animate_do: ^3.3.4
  material_text_fields: ^1.0.4
  dio: ^5.4.3+1
  get: ^4.6.6
  fluttertoast: ^8.2.5
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  path_provider: ^2.1.3
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/jamugo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/jamugo.png"
