// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUj6sRg8Su_wdR__HkN1GfS9QVUAZrqRU',
    appId: '1:880131574846:web:fe07a6744b7104ff83156f',
    messagingSenderId: '880131574846',
    projectId: 'jamugo-firebase',
    authDomain: 'jamugo-firebase.firebaseapp.com',
    storageBucket: 'jamugo-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_VA0L6H2JOCwCnYA1pDzRZ5vB3ggtOOQ',
    appId: '1:880131574846:android:0603918248a1436683156f',
    messagingSenderId: '880131574846',
    projectId: 'jamugo-firebase',
    storageBucket: 'jamugo-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA8Uc31CakLoJLr5nfqyXxA9lHPpXYjbc',
    appId: '1:880131574846:ios:2808762962eb32c683156f',
    messagingSenderId: '880131574846',
    projectId: 'jamugo-firebase',
    storageBucket: 'jamugo-firebase.appspot.com',
    iosBundleId: 'com.example.jamugo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA8Uc31CakLoJLr5nfqyXxA9lHPpXYjbc',
    appId: '1:880131574846:ios:2808762962eb32c683156f',
    messagingSenderId: '880131574846',
    projectId: 'jamugo-firebase',
    storageBucket: 'jamugo-firebase.appspot.com',
    iosBundleId: 'com.example.jamugo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUj6sRg8Su_wdR__HkN1GfS9QVUAZrqRU',
    appId: '1:880131574846:web:93cf43669bcf081e83156f',
    messagingSenderId: '880131574846',
    projectId: 'jamugo-firebase',
    authDomain: 'jamugo-firebase.firebaseapp.com',
    storageBucket: 'jamugo-firebase.appspot.com',
  );
}
